# Generated by Django 4.0.dev20210629100330 on 2022-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('owner', models.CharField(max_length=50)),
                ('workersList', models.CharField(blank=True, max_length=50)),
                ('workerGroup', models.CharField(blank=True, max_length=50)),
                ('data', models.TextField(max_length=255)),
            ],
        ),
    ]
